Adds simple json output.

diff --git a/tinystatus b/tinystatus
--- a/tinystatus
+++ b/tinystatus
@@ -9,6 +9,7 @@ OUTAGE_RC=false
 TIMEOUT=10
 USER_AGENT="User-Agent: Mozilla/5.0 (X11; Linux x86_64; Debian) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36"
 TMP_DIR="$(mktemp -d)"
+OUTPUT_JSON=1
 
 command_exists(){
     if ! command -v "${1}" >/dev/null 2>&1; then
@@ -74,63 +75,89 @@ done < "${CHECKS_FILE}"
 wait
 OUTAGES_COUNT="$(ls "${TMP_DIR}/"*.ko | wc -l)"
 
-# Generate HTML
-cat << EOF
-<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><title>${TITLE}</title><style>
-:root { color-scheme: light dark; }
-body { font-family: segoe ui,Roboto,Oxygen-Sans,Ubuntu,Cantarell,helvetica neue,Verdana,sans-serif; }
-h1 { margin-top: 30px; }
-ul { padding: 0px; }
-li { list-style: none; margin-bottom: 2px; padding: 5px; border-bottom: 1px solid #ddd;  }
-.container { max-width: 600px; width: 100%; margin: 15px auto; }
-.panel { text-align: center; padding: 10px; border: 0px; border-radius: 5px; }
-.failed-bg  { color: white; background-color: #E25D6A; }
-.success-bg { color: white; background-color: #52B86A; }
-.failed  { color: #E25D6A; }
-.success { color: #52B86A; }
-.small { font-size: 80%; }
-.status { float: right; }
-</style></head>
-<body>
-<div class='container'>
-<h1>${HEADER}</h1>
-EOF
-if [ "${OUTAGES_COUNT}" -ne 0 ]; then
-    echo "<ul><li class='panel failed-bg'>${OUTAGES_COUNT} Outage(s)</li></ul>"
-else
-    echo "<ul><li class='panel success-bg'>All Systems Operational</li></ul>"
-fi
-cat << EOF
-<h1>Services</h1>
-<ul>
-EOF
-for file in "${TMP_DIR}/"*.ko; do
-    [ -e "${file}" ] || continue
-    echo "<li>$(cat "${file}") <span class='small failed'>($(cat "${file}.info"))</span><span class='status failed'>Disrupted</span></li>"
-done
-for file in "${TMP_DIR}/"*.ok; do
-    [ -e "${file}" ] || continue
-    echo "<li>$(cat "${file}") <span class='status success'>Operational</span></li>"
-done
-cat << EOF
-</ul>
-<p class=small> Last check: $(date +%FT%T%z)</p>
-EOF
-if [ -f "${INCIDENTS_FILE}" ]; then
-    echo '<h1>Incidents</h1>'
-    if [ -s "${INCIDENTS_FILE}" ]; then
-        sed 's|^\(.*\)$|<p>\1</p>|' "${INCIDENTS_FILE}"
+## If we are outputting simple json, just do that.  Else output HTML.
+if [ "${OUTPUT_JSON}" -eq 1 ]; then
+    if [ "${OUTAGES_COUNT}" -ne 0 ]; then
+        echo "{\"status\":\"degraded_performance\",\"outages\":${OUTAGES_COUNT},\"checked_on\":\"$(date +%FT%T%z)\"}"
     else
-        echo '<p>No incident reported yet ;)</p>'
+        echo "{\"status\":\"operational\",\"outages\":0,\"checked_on\":\"$(date +%FT%T%z)\"}"
     fi
-fi
-cat <<EOF
-</div>
-</body></html>
+    echo "{\"services\": ["
+    for file in "${TMP_DIR}/"*.ko; do
+        [ -e "${file}" ] || continue
+        service_name="$(cat "${file}")"
+        if [ -e "${file}.info" ]; then
+            service_info="$(cat "${file}.info")"
+        else
+            service_info="Unknown error"
+        fi        
+        echo "  {\"name\":\"${service_name}\", \"status\":\"disrupted\", \"info\":\"${service_info}\"},"
+    done
+    for file in "${TMP_DIR}/"*.ok; do
+        [ -e "${file}" ] || continue
+        service_name="$(cat "${file}")"
+        echo "  {\"name\":\"${service_name}\", \"status\":\"operational\"},"
+    done
+    echo "]}"
+else 
+    # Generate HTML
+    cat << EOF
+    <!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><title>${TITLE}</title><style>
+    :root { color-scheme: light dark; }
+    body { font-family: segoe ui,Roboto,Oxygen-Sans,Ubuntu,Cantarell,helvetica neue,Verdana,sans-serif; }
+    h1 { margin-top: 30px; }
+    ul { padding: 0px; }
+    li { list-style: none; margin-bottom: 2px; padding: 5px; border-bottom: 1px solid #ddd;  }
+    .container { max-width: 600px; width: 100%; margin: 15px auto; }
+    .panel { text-align: center; padding: 10px; border: 0px; border-radius: 5px; }
+    .failed-bg  { color: white; background-color: #E25D6A; }
+    .success-bg { color: white; background-color: #52B86A; }
+    .failed  { color: #E25D6A; }
+    .success { color: #52B86A; }
+    .small { font-size: 80%; }
+    .status { float: right; }
+    </style></head>
+    <body>
+    <div class='container'>
+    <h1>${HEADER}</h1>
 EOF
+    if [ "${OUTAGES_COUNT}" -ne 0 ]; then
+        echo "<ul><li class='panel failed-bg'>${OUTAGES_COUNT} Outage(s)</li></ul>"
+    else
+        echo "<ul><li class='panel success-bg'>All Systems Operational</li></ul>"
+    fi
+    cat << EOF
+    <h1>Services</h1>
+    <ul>
+EOF
+    for file in "${TMP_DIR}/"*.ko; do
+        [ -e "${file}" ] || continue
+        echo "<li>$(cat "${file}") <span class='small failed'>($(cat "${file}.info"))</span><span class='status failed'>Disrupted</span></li>"
+    done
+    for file in "${TMP_DIR}/"*.ok; do
+        [ -e "${file}" ] || continue
+        echo "<li>$(cat "${file}") <span class='status success'>Operational</span></li>"
+    done
+    cat << EOF
+    </ul>
+    <p class=small> Last check: $(date +%FT%T%z)</p>
+EOF
+    if [ -f "${INCIDENTS_FILE}" ]; then
+        echo '<h1>Incidents</h1>'
+        if [ -s "${INCIDENTS_FILE}" ]; then
+            sed 's|^\(.*\)$|<p>\1</p>|' "${INCIDENTS_FILE}"
+        else
+            echo '<p>No incident reported yet ;)</p>'
+        fi
+    fi
+    cat <<EOF
+    </div>
+    </body></html>
+EOF
+fi
 
 # Cleanup and exit
-rm -r "${TMP_DIR}" 2>/dev/null
+# rm -r "${TMP_DIR}" 2>/dev/null
 if "${OUTAGE_RC}"; then
     exit "${OUTAGES_COUNT}"
 fi
